### ISSUE TITLE
Fix timeseries visualization for OHB data

### ISSUE THREAD

**Issue by sdivad** [DECODEproject/bcnnow#27]
Like in the visualizations of noise sensor data, when clicking on a point on the map, a new panel is opened on the right side, with a graph showing the temporal evolution for that point (for example, the temporal evolution of monthly rent prices over years in a given district, clicking on this map: https://goo.gl/UcGdHv )
However, although on the background it is possible to see the graph, the panel appears as if it was trying to load something.

**Comment by rohit13k** [comment]
This is the error we are getting in js may be that is the issue
main.js:957 Uncaught ReferenceError: turf is not defined
    at e.<anonymous> (main.js:957)
    at e.fire (leaflet.js:5)
    at e._fireDOMEvent (leaflet.js:5)
    at e._handleDOMEvent (leaflet.js:5)
    at HTMLDivElement.r (leaflet.js:5)


@mirkomarras Any idea about this?

**Comment by rohit13k** [comment]
Done 

The js file turf.min.js was missing
