### ISSUE TITLE
Set the path to bcnnow (ONLY) in the configuration file

### ISSUE THREAD

**Issue by elaragon** [DECODEproject/bcnnow#6]
The path to bcnnow is hardcoded in every collector with the following instruction:
`sys.path.append('/home/code/projects/decode-bcnnow/')`

This should be done as parameter in Config.py instead

**Comment by rohit13k** [comment]
Removed all sys.path.append from code

Now everyone should just set PYTHONPATH variable to the root of the code 

for linux do 

export PYTHONPATH=<path of your root folder for code>

For Windows add aenviornment variable PYTHPATH

@elaragon @franciscogutierres can you guys please confirm if this works for you too.
