### ISSUE TITLE
Remove ngrok 

### ISSUE THREAD

**Issue by rohit-nlp** [DECODEproject/bcnnow#61]
remove ngrok and configure the webapp on port 80 and puthon api on port 8080. raise tickets for port opening if needed.

**Comment by elaragon** [comment]
This was already indicated at https://github.com/DECODEproject/bcnnow/issues/60

Please remember that changing this in the production server should involve people in charge of the app and of the Decidim instance

**Comment by rohit-nlp** [comment]
done
